# название рабочего процесса
name: Demo Workflow
# тесты запускаются в ручном режиме
on: workflow_dispatch
# задаём работу
jobs:
  # название работы, показывает заданное имя в интерфейсе
  print:
    # задаём базовые параметры для "jobs"
    # runs-on принимает описания на какой машине, на каком сервере, с какой операционной системой нам необходимо запустить данный workflow
    # поддерживаются ubuntu, linux, windows and macOs
    # нижеследующая команда запускает выполнение на ubuntu последней версии
    runs-on: ubuntu-latest
    # jobs: может состоять из множества шагов, далее мы их описываем
    steps: 
      # указываем произвольное имя шага
      - name: Print to console
        # пишем команду в консоль, в нашем случае на платформе ubuntu
        run: echo Hello GH Actions!
        # создаём ещё один шаг
      - name: Print a new lines
        # для того чтобы вывести несколько команд ставим знак " | "
        run: |
          echo First line
          echo Second line
        
 # я создал рабочий процесс с именем 'Demo Workflow', поставил указание запускать его вручную, задал работу которая запускает север с ubuntu и выполняет один шаг
 # с названием 'Print to console', который выводит в консоль надпись 'Hello GH Actions'   
 # создаю ещё один шаг с именем 'Print a new line" который выводит в консоль строки 'First line' and 'Second line'. 
 # для того чтобы прописать несколько команд ставлю знак " | "
        
      
  
